### ISSUE TITLE
booting halts after errors, takes 30 > seconds to continue booting

### ISSUE THREAD

**Issue by star-buck** [netrunner-rolling/netrunner-rolling-issues#1]
* BOOT from LIVE usb:
* startup process halted due to:
 switch_root: failed to unlink ro_branch
 "Rebuild dynamic linker cache"

See video of Netrunner 2015.09 pre6d:
https://www.dropbox.com/s/pbppxkp4rs06udy/boot-halted.mp4?dl=0

**Comment by AJSlye** [comment]
OK, from the video you posted the timer for mhwd-live-service started at 22
sec. and ended at 36 sec. this is only 14 seconds for this service to run.
Systemd no longer outputs services to the txt console that it runs itself,
only external services that are not part of systemd will show here.

Once booted, open a terminal and execute the command "systemd-analyze
blame" to see the list of all services started and how long each took.
Running "systemd-analyze" without blame will give you the overall time
systemd took to run all services at boot.
http://www.freedesktop.org/software/systemd/man/systemd-analyze.html

**Comment by star-buck** [comment]
The service runs exactly for 36 seconds... the counter comes up at 22,
showing the service is running for 22 already. On a debian systemd system
on rpi2, the whole boot takes 15 seconds, full netrunner including
owncloud...

**Comment by star-buck** [comment]
Also please check the other two errors, so the usb live boot is
error-free.

**Comment by AJSlye** [comment]
The switch_root: failed to unlink ro_branch is part of loading the overlay
and this is the response I got from that ticket:
https://github.com/manjaro/manjaro-tools/issues/137

The plymouthd issue has been discussed and there is no way to fix this ATM,
this only happens at startup not shutdown.

On Ubuntu / Debian they are still using an older version of systemd and it
is a hybrid init ATM, they are still utilizing upstart for some services.
The timer starts at 22 seconds because that is when it started mhwd, prior
to that it was starting other services. When you run systemd-analyze blame
it lists services in the revers order starting with the last one run to the
first one, Also this is done in parallel so these numbers can not be added
together to give the exact amount of time it took to run them all.

In order for me to fix these I would have to rewrite Manajro tools to load
the graphics stack differently, and use a different method to unmount FS in
overlayfs and/or aufs, and find the bug in plymouthd itself and patch it.

**Comment by AJSlye** [comment]
Also the switch_root: failed to unlink ro_branch has been showing in Arch
Linux for years now, and manjaro is based on arch.

**Comment by AJSlye** [comment]
Philip just posted this on the other ticket that I opeened: https://github.com/manjaro/manjaro-tools/issues/136#issuecomment-141708313

**Comment by AJSlye** [comment]
I think the switch_root: failed to unlink ro_branch issue is caused by aufs/overlayfs exporting to nfs: http://aufs.sourceforge.net/aufs.html#Exporting Aufs via NFS

**Comment by AJSlye** [comment]
OK, getting some help from upstream now.

philip is looking into the switchroot issue:
https://github.com/manjaro/manjaro-tools/issues/137#issuecomment-141684436

Ramon has made some changes to Manjaro-tools-livecd that is now in unstable that loads more services in parallel, this won't change how long mhwd-live takes but it will allow more services to run at the same time reducing the overall boot time. 
https://github.com/manjaro/manjaro-tools/issues/136#issuecomment-141708107

Have you tried disabling quite splash to see the services as they load, instead of just these three scripts?

**Comment by AJSlye** [comment]
Phillip has fixed the  switch_root: failed to unlink ro_branch issue in Manjaro tools.
I'm updating Manjaro tools git on my system tonight and will build an internal test ISO against Unstable. For this one ISO i will be disabling plymouth and removing quiet splash from grub so we can see the entire boot process and not just the scripts in the txt console.

**Comment by star-buck** [comment]
done
